name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore
